spring:
  application:
    name: msmonthlypayment

server:
    port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
