version: '3.8'

services:
  eurekaserver:
    build:
      context: ./eurekaserver
    image: ms-eurekaserver-image
    container_name: ms-eurekaserver-container
    ports:
      - "8761:8761"
    networks:
      - network-ms-copyimagem

  mspersistence:
    build:
      context: ./mspersistence
    image: ms-persistence-image
    container_name: ms-persistence-container
    depends_on:
      - eurekaserver
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - DB_PASSWORD_POSTGRESQL=${DB_PASSWORD_POSTGRESQL}
      - DB_USERNAME_POSTGRESQL=${DB_USERNAME_POSTGRESQL}
    networks:
      - network-ms-copyimagem

  msmonthlypayment:
    build:
      context: ./msmonthlypayment
    image: ms-monthlypayment-image
    container_name: ms-monthlypayment-container
    depends_on:
      - eurekaserver
      - mspersistence
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - DB_PASSWORD_POSTGRESQL=${DB_PASSWORD_POSTGRESQL}
      - DB_USERNAME_POSTGRESQL=${DB_USERNAME_POSTGRESQL}
    networks:
      - network-ms-copyimagem

  ms-help-desk:
    build:
      context: ./ms-help-desk
    image: ms-help-desk-image
    container_name: ms-help-desk-container
    depends_on:
      - eurekaserver
      - mspersistence
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - DB_PASSWORD_POSTGRESQL=${DB_PASSWORD_POSTGRESQL}
      - DB_USERNAME_POSTGRESQL=${DB_USERNAME_POSTGRESQL}
    networks:
      - network-ms-copyimagem

  ms-user-service:
    build:
      context: ./ms-user-service
    image: ms-user-service-image
    container_name: ms-user-service-container
    depends_on:
      - eurekaserver
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - DATABASE_URL_USERS=${DATABASE_URL_USERS}
      - DB_PASSWORD_POSTGRESQL=${DB_PASSWORD_POSTGRESQL}
      - DB_USERNAME_POSTGRESQL=${DB_USERNAME_POSTGRESQL}
    networks:
      - network-ms-copyimagem

  mscloudgateway:
    build:
      context: ./mscloudgateway
    image: ms-cloudgateway-image
    container_name: ms-cloudgateway-container
    depends_on:
      - eurekaserver
      - mspersistence
      - msmonthlypayment
      - ms-help-desk
      - ms-user-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
    networks:
      - network-ms-copyimagem

networks:
  network-ms-copyimagem:
    driver: bridge