version: '3.8'

services:
  eurekaserver:
    build:
      context: ./eurekaserver
    image: ms-eurekaserver-image
    container_name: ms-eurekaserver-container
    ports:
      - "8761:8761"
    networks:
      - network-ms-copyimagem

  mspersistence:
    build:
      context: ./mspersistence
    image: ms-persistence-image
    container_name: ms-persistence-container
    depends_on:
      - eurekaserver
    environment:
      - EUREKA_SERVER_HOST=ms-eurekaserver-container
    networks:
      - network-ms-copyimagem

  msmonthlypayment:
    build:
      context: ./msmonthlypayment
    image: ms-monthlypayment-image
    container_name: ms-monthlypayment-container
    depends_on:
      - eurekaserver
      - mspersistence
    environment:
      - EUREKA_SERVER_HOST=ms-eurekaserver-container
    networks:
      - network-ms-copyimagem

  mscloudgateway:
    build:
      context: ./mscloudgateway
    image: ms-cloudgateway-image
    container_name: ms-cloudgateway-container
    depends_on:
      - eurekaserver
      - mspersistence
      - msmonthlypayment
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_HOST=ms-eurekaserver-container
    networks:
      - network-ms-copyimagem

networks:
  network-ms-copyimagem:
    driver: bridge