CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    last_password_reset VARCHAR(255),
    code_authenticator VARCHAR(255),
    login_attempts     INT,
    locked            BOOLEAN
);

CREATE TABLE user_profiles
(
    user_id BIGINT,
    profiles VARCHAR(255),
    PRIMARY KEY (user_id, profiles ),
    FOREIGN KEY (user_id) REFERENCES users (id)
);